### ISSUE TITLE
2003-plus shares sample folder with 2003

### ISSUE THREAD

**Issue by mediamoshpit** [arcadez/mame2003-plus-libretro#1]
Currently, the 2003-plus core shares a sample folder with the 2003 core. Seeing as how they make use of several different samples, the two can't really coexist without issues.

**Comment by arcadez** [comment]
Actually they can coexist if you think about it a little more, right both cores are looking in the
same place for the same sample eg dkong.zip but both cores are expecting different sample
names to be inside said dkong.zip the key is to merge em then you will have a sample that
can be used across both cores at the same time

So the original core will load the older samples and this core will load the newer samples all from
the same dkong.zip as you'll be adding both sets of samples into the one file if you catch my
drift..???

**Comment by mediamoshpit** [comment]
Ah, ok. I didn't know they were there was a different naming scheme. So, I take it that all the unique samples to this core have a different name? Is there a list as to what those names are. I looked through the commit comments and didn't see a reference, but I might have missed it. Regarding the ROM, I believe my issue was with an incomplete transfer. After I sent the same file again, the game launched fine.

**Comment by dankcushions** [comment]
you might get away with dkong samples being in a merged file (although that adds a step to the user to manually merge them), but sharing this file will cause more problems. eg: hiscore.dat is kept in the same system_dir, but if roms appear differently in memory between these updated roms, that will cause issues for plus when using the shared hiscore.dat. it'll start reading and writing to the wrong memory ranges.

also, the hardcoded emu name will cause issues with all the savefile generated stuff:
/libretro savefile dir/mame2003/diff/
/libretro savefile dir/mame2003/nvram/
/libretro savefile dir/mame2003/hi/
/libretro savefile dir/mame2003/cfg/
/libretro savefile dir/mame2003/inp/
/libretro savefile dir/mame2003/memcard/
/libretro savefile dir/mame2003/snap/

eg, are the internal memory savefiles (.nv/nvram) compatible across both versions?

also, i think the all the core options should be renamed to mame2003-plus. eg: https://github.com/libretro/mame2003-libretro/blob/604844b2a0cd76890289049f3a823ae76172816c/src/libretro/libretro.c#L43
- probably want to have unique entries for this core to allow them to be configured separately.

**Comment by mediamoshpit** [comment]
I merged the samples and even found an existing sample with the files merged and neither produced sound in dkongx with mame2003-plus. All are named correctly according to [your previous post](https://retropie.org.uk/forum/post/121986), but I still may be missing something. I realize github isn't really the place for support issues, but I thought I'd at least document my personal experience here. To that end, I'll also note that I was able to get dkongx to run in lr-fbalpha and get full audio with the merged samples.

**Comment by arcadez** [comment]
@dankcushions i agree totally i'll make a start on this shortly.
@mediamoshpit  forget what i said before i'll setup seperate paths for this core

**Comment by arcadez** [comment]
Ok i think i've done it correctly but this core should now be a seperate standalone version which
can in theory be used alongside the original mame2003 core, i've also went ahead and updated
the retropie setup file for ir-mame2003-plus.sh

Fingers crossed all is well if not then lemmie know and hopefully i can put it right :)
