### ISSUE TITLE
welcome to the libretro buildbot!

### ISSUE THREAD

**Issue by markwkidd** [arcadez/mame2003-plus-libretro#13]
Well @arcadez , mame2003-plus is starting to roll out onto RetroArch on about a dozen more platforms supported by the buildbot. Woo!

This should make it easy for you to try out some of those games with higher memory requirements on your own PC if you want to -- but either way we'll make sure to give them a try :+1: :+1: 

![screenshot 2018-03-25 12 22 19](https://user-images.githubusercontent.com/19554678/37877309-4bf3b9d4-3027-11e8-8577-0228a43793fd.png)

**Comment by arcadez** [comment]
Nice one!! my MAME and FBA code dabbling has been confined to the xbox and xbox360
until this moment, hopefully all the people using the many platforms listed above might
get some small enjoyment outta this updated core.

Cheers!!

**Comment by grant2258** [comment]
well guys youve all done a great job glad to be part of this
