### ISSUE TITLE
Spiderman the video game speed and voice speech missing bug

### ISSUE THREAD

**Issue by cecilmax** [arcadez/mame2003-plus-libretro#22]
There is a serious glitch for spiderman the video game on wii with retroarch 1.7.1

And if we watch this video, spiderman at 0:25 speak for couple of seconds, when playing that voice is missing....
https://www.youtube.com/watch?v=QVEH-i2qp8M

I try to speed it up with:
static MACHINE_DRIVER_START( system32 )

	/* basic machine hardware */
	//MDRV_CPU_ADD(V60, OSC_A/2/12) // Reality is 16.somethingMHz, use magic /12 factor to get approximate speed
	MDRV_CPU_ADD(V60, 100000) // Reality is 16.somethingMHz, use magic /12 factor to get approximate speed

the intro of the game is now fine. Once in the game it is still very slow ...

**Comment by arcadez** [comment]
Well this worked on the Xbox but not so much on the Wii i guess.

MDRV_CPU_ADD(V60, 14000000 )// should be 16mhz but make it this to speed things up for the Xbox

Look im gonna close this soon ok as this a dev libretro plus it's not a problem with this core per say
more a case of the platform your using and there's nothing that can be done about this less you
upgrade to more powerfull hardware.

**Comment by cecilmax** [comment]
I wonder if on xbox it have the voice at the beginning at 0:25 ?

I just test it on Wii U, same result..

**Comment by markwkidd** [comment]
@arcadez I have a feeling you know this already but within libretro if there is a fix needed for a certain platform we have some platform-specific compiler flags we can use.

For example this kind of code would work in general (I have not tested/may have mistakes and typos)

if define(WIIU)
MDRV_CPU_ADD(V60, 14000000 )// should be 16mhz but make it this to speed things up for the Wiiu
else
MDRV_CPU_ADD(V60, 16000000 )
endif

**Comment by arcadez** [comment]
Yeah it's not really a fix per say i just thought it was worth a try to see if the game
would get a performance boost, i forgot though i had updated my V60 for my
Xbox core which means the clock handling changed.

Basically the CPU used to divide all the clocks and they changed it to take a straight
value thats maybe why 14000000 didn't work.?? or maybe it did and the Wii still cant
handle it, anyway it's not a code change worth making for the core.

Oh BTW i didn't know about those flags i really should investigate the libretro side of
things a little more ;) @markwkidd can i ask ya a quick favor can you add your default
nvram changes for run and gun to this core when you get a spare moment or two.

**Comment by cecilmax** [comment]
Are you sure its a limitation of the Wii ? I test it on Wii U that have a ram of 2gb and it is still slow ..

I wonder where the function ROM_START () is defined ? I will try to investigate ..

**Comment by arcadez** [comment]
Well all of the Sega System 32 and Multi32 games are full speed on the Xbox, so I can
only assume the reason they are slow on the Wii and Wii U is those consoles cant get
the job done ;)

**Comment by cecilmax** [comment]
Good point ;) but I test it in vWii on wii U not on real Wii U. I think the vWii is just like the real wii..

**Comment by cecilmax** [comment]
Can you give me somes infos ? I try to understand the code, as example, where rom_start function is defined ?

I am not very familiar with c..as example, how the engine know it have to use which rom start there is many in the same .c ?
