### ISSUE TITLE
i think we should pull these changes in arcadez its up to you though

### ISSUE THREAD

**Issue by grant2258** [arcadez/mame2003-plus-libretro#23]
my m68k core update fixed altered beast head missing and game not working maybe other bug we dont know about yet

https://github.com/libretro/mame2003-libretro/pull/342

ym2151

https://github.com/libretro/mame2003-libretro/pull/345

**Comment by arcadez** [comment]
You don't have to ask me bigman!! just go ahead and make the changes that you guys
want to and if anything was to get broken in the process then it can always get fixed
down the road :)

**Comment by arcadez** [comment]
Tell ya what hang off for now i'm trying to add sound to a game that doesn't have it in this
core i've added a new sound file to sndhrdw and hooked it upto the driver in question
if this pans out i'll need to make some changes to 2151_intf.c and ym2151.c so it's best
to wait till after i do before porting the your commits across.

Feel free to update the mushi core though if you want.

**Comment by grant2258** [comment]
ok no problems its just on line added anyway the update might have it.
