### ISSUE TITLE
Missing game sets between lr-mame2003 and mame2003-plus

### ISSUE THREAD

**Issue by Wilstorm** [arcadez/mame2003-plus-libretro#24]
I am not sure if it's an issue but more just an observation. These 2 sets were in the original lr-mame2003 DAT but have been removed from Plus. After comparing the two DATs these are the only 2 that have been completely removed for some reason. The rest are 100% the same minus the updates and additions.

**Comment by grant2258** [comment]
from riverstrom on retropie forums 

A couple of sets I see that were in lr-mame2003 but have been removed from mame2003-plus.

    Cabal (US set 2) (cabal2)
    Urashima Mahjong (urashima)

**Comment by arcadez** [comment]
I updated the Cabal driver to add support for the superior joystick version, sometimes rom 
names change between different MAME releases and the descriptions also for example 
Cabal set2 becomes.........

GAME( 1988, cabalus2,cabal, cabal,   cabalt,   cabal,   ROT0, "Tad (Fabtek license)", "Cabal (US set 2, Trackball version)" )

As for that Mahjong game it was a victim of my NMK16 driver update but it didn't work anyway.
