### ISSUE TITLE
ios linking error with mustache.o

### ISSUE THREAD

**Issue by markwkidd** [arcadez/mame2003-plus-libretro#30]
Something in the new `mustache.c` seems to be tripping up the ios compiler. Here are the logs: http://p.0bl.net/178797

**Comment by arcadez** [comment]
Well this is a pisser isn't it, notice all the hits are on the the t5182 and nothing from darkmist.c
which is using the same sound handling makes me suspect the ios compiler is being a cunt
around the same code being defined in both drivers..?? 

Anyway on spec to confirm this or not i'll remove darkmist for now.

**Comment by arcadez** [comment]
@markwkidd i think it's fixed now eh.?? certainly there are still some build failures but
from checking the logs those were there from before and not connected to the changes
i made yesterday.??

Might as well leave the t5182 soundcore active in the build if it along with mustache.c
will now compile i'll look at fixing the conflicts with darkmist if possible down the road.
