### ISSUE TITLE
YM2151 issue on altbeast

### ISSUE THREAD

**Issue by grant2258** [arcadez/mame2003-plus-libretro#32]
the sound has problems on the YM2151 i updated the cpu core its not that causing it it was doing it before the update to the 68k core. Just to save you the time checking that out arcadez

**Comment by grant2258** [comment]
ill try with  define USE_MAME_TIMERS when i get up am blury eyed from work need some sleep

**Comment by arcadez** [comment]
Yeah some of the Sega System 16 and 18 games have bad sound in this older core, this was
fixed in later mame around 82 i think, these improvements are not connected to the YM2151
sound core they were done in driver and machine files

**Comment by grant2258** [comment]
the sound works for these games on the on mame 078 and 2003 just getting a hybrid sound of white like noise now

**Comment by arcadez** [comment]
Maybe i got mixed up with Shinobi..?? there was defo a sound improvement for that game
a few builds after MAME78

**Comment by grant2258** [comment]
I love shinobi is one of may favs. Ill go through the system16 games and see if its just them twp i know the sound is broke broke in golden axe now as well

**Comment by arcadez** [comment]
It might have been that way before but hey if my changes to the timer code are responsible
for any breakage then i can always revert em back, as adding sound to one game is no good
if it's gonna break the sound in many more :)

I fully tested these changes and they work perfectly fine but that's with another MAME core
on a different platform im confident the code will be good for this core also but there's
never a 100% guarantee when switching code between cores.

**Comment by grant2258** [comment]
Leave it fir now till we see what's causing it. I didn't test before the
update. Only reason I used altered beast is because it was a 68kcore bug
game

**Comment by arcadez** [comment]
https://retropie.org.uk/forum/topic/4632/sound-issues-with-sega-system-16-games/2

**Comment by grant2258** [comment]
I'm not having issues with the sound I think some volume levels are louder
than the should but in altered beast. There is 2 sets for altered beast one
with bad sound and one with good sound

**Comment by grant2258** [comment]
well its not the ym2151 changes doing it its something else even with the original in the behavior is the same

**Comment by grant2258** [comment]
splatter (splatterhouse) sound is broke as well before and after the ym2151 changes there is something going on here.  Is the sound woking ok for you on these games arcadez?

**Comment by grant2258** [comment]
found the problem arcadez hope it doesnt brake what you fixed in the first place

**Comment by arcadez** [comment]
I never noticed any problems with Splatter House my end, but your commit causes no
issues in Mustache Boy the sound still works fine in that one.

**Comment by arcadez** [comment]
Ok so i tested a few Sega System 16 games there was some niggles around the sfx
either being missing at times or plain triggering wrongly while some sounds are a bit
scratchy and therefore kinda not to nice on the ole ears, i think from reading some
posts over at the Rpi forums they were this way before my recent YM2151 changes.

Altered Beast
seems ok for the most part some of the sfx is scratchy though

Golden Axe
worst outta the ones i tested some missing sfx while other sounds will play incorrectly
or drop out randomly plus horrible sounds when enemies die.

Shinobi
Horrible sounds when your charcter jumps up and down from the platforms in the levels
also missing Sfx when you trigger the special move

**Comment by grant2258** [comment]
well the problem was the sample where playing but no music just changed.I think its just volume levels in the samples its back to the way it was now. It better to try fix things rather than ditch them
