### ISSUE TITLE
Speed issue with game Ninja baseball bat man

### ISSUE THREAD

**Issue by cecilmax** [arcadez/mame2003-plus-libretro#35]
Hello,

there is speed issue with this game on wii. it run very slow, sound and graphics. Other m92 game run fine, only this one have issue.

Maybe somes games just need adjustments to run on Wii ... like Denjin Makai (it doesnt run at all on wii) but it does on FBA.. or spiderman (it just need speed adjustment) etc.

**Comment by arcadez** [comment]
Listen this is just a WIP MAME core there is no guarantee that every game that works in FBA will work
in this core or vice versa, but how about you read this thread and then discuss with the WII dev's 
if some of these changes can be implemented for the Wii FBA or MAME cores............

https://github.com/libretro/fbalpha/issues/188
