### ISSUE TITLE
sound support for Fire Shark and others?

### ISSUE THREAD

**Issue by markwkidd** [arcadez/mame2003-plus-libretro#36]
@AriaOnThePlanetes was asking about this in Discord, and I encouraged them to post an Issue here but they did not.

In very recent MAME versions, the HD647180 ROM has finally been dumped after years without it. The filename is hd647180.017. @AriaOnThePlanetes also says that "I think Teki Paki, Whoopee and Ghox also could have sound with dumped hd647180 data."

I wanted to start this issue to track the idea in case it may pan out later.

**Comment by arcadez** [comment]
I've done Fire Shark / Same Same Same and Vimana for this core, with regards Teki Paki 
and Whoopee i ran into some incompatable code so i was unable to backport the sound 
MCU dump for those games.

With regards to Ghox i did backport all the code but afterwards the game didn't function
correctly i think the Z180 CPU core wasn't correct for this in these ole MAME cores
and i didn't fancy attempting to update it.

But the next FBA for which you guys have a core will support all of the HD647180
sound MCU dumps come the next release which i hear should be next weekend

Regards.

**Comment by markwkidd** [comment]
Sounds conclusive to me -- closing this issue.
