### ISSUE TITLE
Taito double and triple screen games

### ISSUE THREAD

**Issue by arcadez** [arcadez/mame2003-plus-libretro#40]
These could be annoying as they'll boot as a tiny slither of graphics across the centre of
the screen we used to change the display in our xbox MAME emulators to make the games
boot single screen.

We found a better way to do via a small aspect ratio display change in the driver similar deal
as with Tecmo Bowl it would be a doddle to set this up for this core should it be needed
unless you have a workaround already..??

games are..........

Darius
Darius 2 (dual screen) 
Darius 2 (Triple Screen) 
The Ninja Warriors
Warrior Blade - Rastan Saga Episode III

**Comment by ZappaUtopia** [comment]
These games need the 2/3 screens because the display is spread between them. If you remove one then you won't be able to see whats going on.

**Comment by arcadez** [comment]
Sure but when it loads as a tiny slither across the middle of my TV screen then i cant really
see what's goin on anyway, ok i'll close this and just leave the games be as there will be 
manual screen resize options in the emulator menu

**Comment by arcadez** [comment]
Yeah i recall the same thing happening with PC MAME also, but that was some years back now
i guess the Rpi devs have already taken care of this.
