### ISSUE TITLE
access to this repository / adding it to libretro buildbot

### ISSUE THREAD

**Issue by markwkidd** [arcadez/mame2003-plus-libretro#9]
Hello @arcadez and thanks as always for your work to advance mame2003.

You mentioned you would be willing to give me commit access to this repository. If you would like to do that:
1. I promise to be careful
2. I will add mame2003-plus-libretro to the libretro buildbot which will make this version of the core much more accessible to people who use the RetroArch GUI
3. I will try to help out with the process of merging your improvements back into mame2003 when the time comes for that

Adding me as a collaborator to your repository:
1. Got to https://github.com/arcadez/-mame2003-plus-libretro/issues/new and click on **Settings** from the navigation bar
2. On left click **Collaborators**
3. Type in my username, **markwkidd**

**Comment by markwkidd** [comment]
I just received the notification. Thank you for your confidence.

**Comment by arcadez** [comment]
Ok i've added yourself and grant2258 to the collaborators list as you guys have forked this
and seem keen to work with the core, consider this as much yours now as mine, i'll be
stepping back as i've nothing else i can really backport to this ole src and that was my
main focus really.

**Comment by grant2258** [comment]
thanks for adding arcadez ill leave and changes in marks hand to add or not as im really not great with github yet

**Comment by markwkidd** [comment]
OK, wow, and thank you again @arcadez .

Knowing you are done with your project is a big milestone for mame2003. Congratulations!

## 'classic' mame2003-libretro
@grant2258 has done a lot to 'lock in' a polished version of the 'classic' mame2003 codebase with regard to some previously undocumented bugs as well as the catver.ini and xml gamelist metadata. retro-wertz is working on a (final?) round of enhancements to the lightgun code

I've been working on user interface and input mapping improvements. I have also added a new internal hiscore database.

## mame2003-plus-libretro
If you are done making your enhancements, it's definitely time to start distributing the XML gamelist and encouraging folks to find any bugs. I can be a point of contact with the libretro devs on getting this into the buildbot to make testing easier for more people.

BTW there are #programming and #retroarch channels in the RetroArch Discord chat server where a lot of discussion of libretro development happens if you all use Discord.

As time permits over the next month or two I can try to figure out the best way to merge the two codebases. My first instinct is to start rolling commits from mame2003-libretro into mame2003-plus-libretro one at a time starting when they forked but it's too early to be thinking about that :)

**Comment by arcadez** [comment]
OK no problem for the record i have fully tested every code change and commit i done here
all be it on a MAME72 xbox build whether the same code will function correctly on all the
platforms that might use this core then i cant be sure.

99% of the changes above were isolated in the sense they would only affect the drivers and
their related files and i made sure to test every game in any way affected, so not being corewide
code alterations so to speak i would seriously doubt any other games would have been broken in the proccess

Just a heads up though i was unable for reasons of memory contraint to test the PGM and most
of the larger NeoGeo games so there would be a big question mark over these ones, however
i was able to confirm all of the following Neogeo would be playable should the correct roms 
be used........

Bang Bang Busters
Choutetsu Brikin'ger - iron clad
Crossed Swords 2
Ghost Loop
Last Hope
Zintrick / Oshidashi Zentrix
Zupapa

**Comment by arcadez** [comment]
@markwkidd there will be some opposition to merging the two mame-2003 cores back together
as some people just never agreed with my direction with regards to updating the core, however
they're entitled to their opinion but as such i dont think you'll be able to persuede them otherwise
but then again maybe your a better negotiator than i ever was lol.

But in some ways it's for the best as people then have a choice to stick with mame-2003 with
the set in stone romsets from MAME78 or if people want some more fixes and improvements 
over and above the original core plus some extra game support and are not averse to updating
their roms and a few samples here and there then they can choose to use this core.

Im not sure about renaming it to LiteMAME though as it makes this core sound like the poor
relation to mame-2003 libretro when in my opinion it's the superior version :) but i would say
that i guess, im sure between us we'll come up with something should a core rename be required.

Regards

**Comment by markwkidd** [comment]
more like "lightningMAME"! err that is the name of an old defunct project from 2012.
still could be used. lightning-mame-libretro. LML.

Anyway let's see how it will all work first. I'm running this new XML file through its paces in clrmamepro right now to get a first idea.

**Comment by markwkidd** [comment]
Let's talk more about an awesome new name for mame2003-plus

I'm going to close this issue for now though, unless there is any reason to keep it going.
